source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PNGradientView_Example' do
  pod "PNGradientView", :path => "../"
end

target 'PNGradientView_Tests' do
  pod "PNGradientView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
